### ISSUE TITLE
[Feat] Location Default Place Extract API 개발 

### ISSUE THREAD

**Issue by seochan99** [CSID-DGU/2024-1-CECD1-Tripple-5#16]
## To-do

- [ ] 2중 체인 구조 개발
- [ ] chain1 : Keyword 
- [ ] chain2 : find DB Schema and extract place
- [x] DB 구축 -> postgresSQL
- [x] FastAPI API개발
